[rule]
author = ["KC"]
rule_id = "10000000-4000-400a-b200-4a285d000003"
description = ""
from = "now-6m" #From changes the default lookback time, 6m is default
name = ""
risk_score = 47
severity = ""
tags = [
    "Domain: Endpoint"
]
type = "eql"
# if the rule type is threshold, we need to include a threshold field
# threshold = [value]

query = '''
'''
note = ""

[[rule.threat]] # Example of assigning TTPs
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1114"
name = "Email Collection"
reference = "https://attack.mitre.org/techniques/T1114/"
[[rule.threat.technique.subtechnique]]
id = "T1114.001"
name = "Local Email Collection"
reference = "https://attack.mitre.org/techniques/T1114/001/"

[rule.threat.tactic]
id = "TA0009"
name = "Collection"
reference = "https://attack.mitre.org/tactics/TA0009/"

# Optional fields:
# throttle: 7d
# version: 1
# interval: 5m

# [rule.threshold]
# field = ["host.hostname"]
# value = 100